#!/bin/bash

# enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

source /usr/share/bash-completion/completions/git

# Taken from https://stackoverflow.com/questions/47781631/how-to-auto-complete-a-multi-level-command-aliased-to-a-single-command
# and modified to pass the --repo --tag --id arguments to __docker_complete_images, because
# otherwise the completion results would include stuff like the image size...
_docker_env() {
    local previous_extglob_setting
    previous_extglob_setting=$(shopt -p extglob)
    shopt -s extglob

    _get_comp_words_by_ref -n : cur prev words cword

    # TODO: Include other "docker run" arguments
    # Unfortunately /usr/share/bash-completion/completions/docker is a bit hard to follow, so it's
    # not entirely obvious how to do this.
    declare -F __docker_complete_images >/dev/null && __docker_complete_images --repo --tag --id

    eval "$previous_extglob_setting"
    return 0
}

if [ -f /usr/share/bash-completion/completions/docker ]; then
    source /usr/share/bash-completion/completions/docker
    complete -F _docker_env docker_env
fi
