#!/usr/bin/env bash

# Docker setup

echo "Setting up docker..."

echo -e "\tRemoving any old installation..."
sudo apt-get remove docker-desktop || true
rm -r $HOME/.docker/desktop || true
sudo rm /usr/local/bin/com.docker.cli || true
sudo apt-get purge docker-desktop || true

if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
    echo -e "\tAdding docker GPG key..."
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
fi

if [ ! -f /etc/apt/sources.list.d/docker.list ]; then
    echo -e "\tAdding docker PPA..."
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null

    sudo apt-get update
fi

echo -e "\tInstalling docker..."
sudo apt-get install --no-install-recommends -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-buildx-plugin

if prompt_default_yes "Add $USER to docker group?"; then
    if ! getent group | grep docker; then
        sudo groupadd docker
    fi

    if ! groups | grep docker; then
        sudo usermod -aG docker $USER
    fi

    echo "Be sure to sign out before using docker"
fi

if [ ! -f /etc/docker/daemon.json ]; then
    echo -e "\tInstalling docker daemon config..."
    sudo cp $BOOTSTRAP_ROOT/docker/daemon.json /etc/docker/daemon.json
    sudo systemctl restart docker
fi

sudo docker run --rm -it hello-world
