#!/usr/bin/env bash

echo "Setting up python..."

echo -e "\tInstalling apt packages..."
sudo apt-get install --no-install-recommends -y \
    python-all \
    python-dev-is-python3 \
    python-is-python3 \
    python3 \
    python3-pip \
    python3-venv

echo -e "\tInstalling pip packages..."
python -m pip install cmakelang gcovr pytest
